### PR TITLE
updates list of ignored http status codes for qa check

### PR DESCRIPTION
**Pull request by btylerburton**
# Pull Request

Related to None

## About

Updates list of ignored http status codes for qa link check
## PR TASKS

- [ ] The actual code changes.
- [ ] Tests written and passed.
- [ ] Any changes to docs?
- [x] Any new
      [Gemfile](https://github.com/GSA/resources.data.gov/blob/main/Gemfile)
      or
      [package.json](https://github.com/GSA/resources.data.gov/blob/main/package.json)
      updates to pull in?

### CODE REVIEW

**Comment by nickumia-reisys** [comment]
Does this work?

**Comment by nickumia-reisys** [comment]
I feel like ignoring `999` is a little borderline.

**Comment by btylerburton** [comment]
Yeah it works. Reduces the weekly error count. I removed 999 as well as it was probably too aggressive.

**Review by nickumia-reisys — APPROVED** [review]
🦖

**Comment by nickumia-reisys** [comment]
Related to
- https://github.com/GSA/data-strategy/pull/311#pullrequestreview-1326873723

**Pull request merged**
