### PR TITLE
Create profiles_in_data_sharing_NEISS.md

### PR DESCRIPTION
**Pull request by crysacarter**

### CODE REVIEW

**Comment by crysacarter** [comment]
@jbrown-xentity  when you have a second could you take a look at this? I checked the keywords, etc. like last time, so I'm not sure what I missed.

**Comment by jbrown-xentity** [comment]
@crysacarter , the pdf you are trying to link to doesn't exist in this branch. You made a separate PR for that: https://github.com/GSA/resources.data.gov/pull/519
When you split up content into different PR's at the same time, the system can't handle it. You can either
1. Recreate this PR from `main` with the same content (since the PDF PR is merged, the PDF is in main and this will work)
2. Pull main into this branch ([documentation](https://www.togaware.com/linux/survivor/Git_Merge_Master_into.html))

In the future, I would suggest putting these items in the same commit. If you're not sure how to do that, reach out on Slack and would be happy to walk you through it.

**Comment by crysacarter** [comment]
I'm not sure what I'm missing.  

I see this: 
You can’t commit to main because it is a protected branch. So it creates the new branch.

If I go directly to PRs and click "create new pull request" I get a "compare changes" page and cannot create from there. 

I've read the github docs and I'm just not seeing what I'm doing wrong.  I'm sure it's easier than I'm making it

**Comment by crysacarter** [comment]
corrected request created

**Pull request closed without merging**
