### PR TITLE
Create profile_in_data_sharing_neice.md

### PR DESCRIPTION
**Pull request by crysacarter**
# Pull Request

Related to [LINK TO ISSUE]

## PR TASKS

- [ ] The actual code changes.
- [ ] Tests written and passed.
- [ ] Any changes to docs?
- [ ] Any new
      [Gemfile](https://github.com/GSA/resources.data.gov/blob/main/Gemfile)
      or
      [package.json](https://github.com/GSA/resources.data.gov/blob/main/package.json)
      updates to pull in?

### CODE REVIEW

**Comment by crysacarter** [comment]
@hkdctol This error says that the document that I uploaded yesterday doesn't exist.  I'm unsure how to fix that.  It's in the assets folder.

**Comment by FuhuXia** [comment]
@crysacarter
It is the relative path. Is the new file `profile_in_data_sharing_neice.md` supposed to go into `/pages/`, or `/pages/_resources/`?

**Comment by crysacarter** [comment]
/pages/_resources/ is where the rest of the similar pages are.

**Comment by hkdctol** [comment]
@FuhuXia can you check this out?

**Comment by FuhuXia** [comment]
Yes, `/pages/_resources/` is where the new page should go. But it is added into `/pages/` in this PR. Let me makea new commit and see if it passes the check.

**Review by FuhuXia — APPROVED** [review]

**Comment by FuhuXia** [comment]
@crysacarter It is now live at https://resources.data.gov/resources/profile_in_data_sharing_neice/

**Comment by crysacarter** [comment]
Thank you

**Pull request merged**
