### PR TITLE
Update inventory-data-gov-guide.md

### PR DESCRIPTION
**Pull request by crysacarter**
edits/updates

# Pull Request

Related to [LINK TO ISSUE]

## PR TASKS

- [ ] The actual code changes.
- [ ] Tests written and passed.
- [ ] Any changes to docs?
- [ ] Any new
      [Gemfile](https://github.com/GSA/resources.data.gov/blob/main/Gemfile)
      or
      [package.json](https://github.com/GSA/resources.data.gov/blob/main/package.json)
      updates to pull in?

### CODE REVIEW

**Comment by FuhuXia** [comment]
I don't see the edit I did on the download data.json using api-key part?

**Review by hkdctol — COMMENTED** [review]
@tdlowden could you provide the review on this?

**Comment by tdlowden** [comment]
@FuhuXia or @btylerburton resources is a cloud.gov pages site, correct? Is there a link to a preview I could review, rather than trying to review just the markdown?

**Comment by FuhuXia** [comment]
It must have been this way for a while but we are missing the search icon.
image

**Comment by tdlowden** [comment]
Appears there was a build issue not immediately evident: https://github.com/GSA/resources.data.gov/actions/runs/8454661902/job/23160231383?pr=682#step:6:175

I could not access the preview page by appending the path.

From @jbrown-xentity :

I'm not as familiar with this, but the only thing I notice is that all the other new lines have a tab to start the line, and the one it's complaining about doesn't, so I'm betting that's the issue?
Yeah, that is a problem. I would investigate https://github.com/GSA/resources.data.gov/blob/main/package.json#L42-L44, these are the commands it's running. My gut is that if we add some flag/detail, it will cause the build to fail if a page doesn't get created, but it's not the default...

**Comment by FuhuXia** [comment]
it is the missing tabs. Now you can preview it at 
https://cg-f5a56614-c88e-470c-9f06-ff5fe2d4c98a.sites.pages.cloud.gov/preview/gsa/resources.data.gov/crysacarter-patch-1/resources/inventory-data-gov-guide/

**Comment by FuhuXia** [comment]
This is the edit I was referring to, that is missing from the PR.
https://docs.google.com/document/d/1eyBvxMnBPxE4xlaN4BED_E74_T1_tVHbPjxSG2rKb4c/edit?disco=AAABJ6MvM4s

**Comment by tdlowden** [comment]
I just made some small commits and now getting another error:

image

**Review by tdlowden — APPROVED** [review]

**Pull request merged**
