### PR TITLE
Create 2021_DSWG Recommendations_and_Findings_508.md

### PR DESCRIPTION
**Pull request by crysacarter**

### CODE REVIEW

**Review by hkdctol — APPROVED** [review]

**Comment by crysacarter** [comment]
looks like it failed to build.  Not sure what I'm missing as when I do these, I take the code from one of the prior pages and replace the new information where needed (title, description, etc) - but this also happened last time

**Comment by nickumia-reisys** [comment]
Hi @crysacarter, the reason this failed was because there was a new keyword introduced that had not been previously defined.  The solution is to check the keywords that exist in `pages/_keywords` and make sure all of the words in [the tags section](https://github.com/GSA/resources.data.gov/pull/424/files#diff-76def14fa10b7efda4b4de80b0fcc606c78769a06002f475281705d47f5c2d19R11-R15) have an associating file with the same name in that directory.

**Review by nickumia-reisys — APPROVED** [review]
📑

**Comment by FuhuXia** [comment]
@crysacarter
Other that what @nickumia-reisys mentioned, also be aware that:
When you upload a new PDF, make sure the PDF PR is fully approved and merged before you create the 2nd PR containing the text using the PDF. If you create the 2nd PR too early, it will always fail.

**Pull request merged**
