### PR TITLE
Create communities-of-practice.md

### PR DESCRIPTION
**Pull request by crysacarter**
Tools --->> agency data info

### CODE REVIEW

**Comment by adborden** [comment]
Aren't we just duplicating https://digital.gov/communities/ ?

**Comment by crysacarter** [comment]
Yes in response to a request from Hyon. (See attached)

**Comment by hkdctol** [comment]
@crysacarter we don't want to duplicate all the content from digitalgov which has all the communities in it, just provide open data specific information--I will provide suggested language.

**Comment by hkdctol** [comment]
@crysacarter the content looks fine--did you label as invalid?

**Comment by hkdctol** [comment]
Do not need this content on other communities

**Pull request closed without merging**
