### PR TITLE
Feature/4788 migrate federation

### PR DESCRIPTION
**Pull request by robert-bryson**
# Pull Request

Related to https://github.com/GSA/data.gov/issues/4788

## PR TASKS

- [ ] The actual code changes.
- [ ] Tests written and passed.
- [ ] Any changes to docs?
- [ ] Any new
      [Gemfile](https://github.com/GSA/resources.data.gov/blob/main/Gemfile)
      or
      [package.json](https://github.com/GSA/resources.data.gov/blob/main/package.json)
      updates to pull in?

### CODE REVIEW

**Comment by tdlowden** [comment]
Awesome, thanks @robert-bryson. Will do a more thorough review soon.

**Comment by tdlowden** [comment]
Ok I tried to add something in but ended up making it error.

@robert-bryson can you find a way to add in a bolded note that it's no longer active. Something like:

**NOTE: This project is no longer active. This page serves as an archive of the work performed in the past**

**Comment by tdlowden** [comment]
Aside from that, looks great!

**Comment by tdlowden** [comment]
@robert-bryson  Wish we could bold it, but that's how I threw an error when I tried. C'est la vie

**Comment by robert-bryson** [comment]
It is technically bolded, but I agree that the formatting is too subtle. Ideally would would be able to use a [USWDS alert](https://designsystem.digital.gov/components/alert/#standard-alerts) or something like that. I'll poke a bit and see if I can get the markdown to render an alert.

**Review by tdlowden — APPROVED** [review]
Looks great. I see one failed test though? @robert-bryson how can we clear the error?

**Review by tdlowden — APPROVED** [review]

**Pull request merged**
